swagger: '2.0'
info:
  version: v1
  title: REST API Documentation for the MOTI Hired Equipment Tracking System (HETS) Application
  description: |
    The Hired Equipment Program is for owners/operators who have a dump truck, bulldozer, backhoe or 
    other piece of equipment they want to hire out to the transportation ministry for day labour and 
    emergency projects. 
    The Hired Equipment Program distributes available work to local equipment owners. The program is 
    based on seniority and is designed to deliver work to registered users fairly and efficiently 
    through the development of local area call-out lists.
  termsOfService: N/A
basePath: /api
paths:
