apiVersion: v1
kind: Template
metadata:
  creationTimestamp: null
  name: patroni
labels:
  app: ${NAME}${SUFFIX}
  phase: build
  app.kubernetes.io/component: database
  app.kubernetes.io/name: patroni
  app.kubernetes.io/managed-by: template
  app.kubernetes.io/version: "10"
parameters:
  - name: NAME
    value: patroni
  - name: SUFFIX
  - name: VERSION
    description: Ouput version
    value: "latest"
  - name: GIT_URI
    value: https://github.com/bcgov/hets.git
  - name: GIT_REF
    value: 1.9
  - name: POSTGRES_VERSION
    value: "10"
  - name: NAMESPACE
    value: "bcgov"
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    creationTimestamp: null
    name: ${NAME}
  spec:
    lookupPolicy:
      local: false
  status:
    dockerImageRepository: ""
- apiVersion: v1
  kind: BuildConfig
  metadata:
    creationTimestamp: null
    name: ${NAME}${SUFFIX}
  spec:
    nodeSelector: null
    output:
      to:
        kind: ImageStreamTag
        name: "${NAME}:${VERSION}"
    postCommit: {}
    resources: {}
    source:
      contextDir: patroni/docker
      git:
        ref: ${GIT_REF}
        uri: ${GIT_URI}
      type: Git
    strategy:
      dockerStrategy:
        from:
          kind: DockerImage
          name: docker-registry.default.svc:5000/${NAMESPACE}/patroni:v10-stable
      type: Docker
    triggers:
    - type: ConfigChange
    - imageChange: {}
      type: ImageChange
  status:
    lastVersion: 0